name: artifact
on: push

jobs:
  upload-artifact:
  runs-on: ubuntu-latest
  steps:
  - name: echo
    run: echo hello-world > hello.txt
  - name: upload artifact
    uses: actions/upload-artifact@v3
    with:
      name: artfact-test
      pathes: ./hello.txt

  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
    - name: download artifact
      uses: actions/download-artifact@v3
      with:
        name: artfact-test
        path: ./
    - name: checkout
      run: cat hello.txt